# Generated by Django 5.0 on 2024-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_data', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
