# Generated by Django 5.0 on 2024-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_audiofile_commands_userstexts_delete_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='confirmation',
            field=models.CharField(help_text='Введите ключевые слова запроса', max_length=250, verbose_name='Ключевые слова запроса'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
